### ISSUE TITLE
Why NEON and VFP support is disabled for ARM?

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/pyvex#106]
Hi Guys!

I have noticed that in 

https://github.com/angr/pyvex/blob/a088c6ae76c9b50f2024ce1087ef031e0b611eb0/pyvex_c/pyvex.c#L221-L223

NEON and VFP support is disabled. 

Could you please advise why that limitation has to be imposed?

Thanks.

**Comment by rhelmot** [comment]
There is no reason. I have been enabling flags on a case by case basis because sometimes the flags conflict with each other so just setting -1 doesn't work and it's a lot of work to figure out what the right values to use in each case are. You can submit a PR enabling the maximum arm hwcaps if you like.

**Comment by ArtemShypotilov** [comment]
Hi Audrey,

I have created PR to enable NEON and VFP support. Can you please have a look?

CFGFast contains much more nodes for me now. However , during CFGFast build process I sometimes got errors like:

ERROR:angr.engines.vex.irop:Unsupported operation: Iop_ScaleF64
ERROR:angr.engines.vex.irop:Unsupported operation: Iop_F32ToFixed32Ux4_RZ
ERROR:angr.engines.vex.irop:Unsupported operation: Iop_Widen8Uto16x8
ERROR:angr.engines.vex.irop:Unsupported operation: Iop_Widen16Sto32x4
ERROR:angr.engines.vex.irop:Unsupported operation: Iop_Widen32Uto64x2

What do you think about that? Is it critical?

**Comment by rhelmot** [comment]
Ah, yes, so yes you can ask vex to translate the code, but the actual operations may not be implemented in angr. In terms of cfgfast it's not extremely critical, since simulation is only used for supplementary information purposes, but if you're going to do symbolic execution you'll have a bad time.

The full list of operations is found [here](https://github.com/angr/vex/blob/master/pub/libvex_ir.h#L403), and our implementations of it are found [here](https://github.com/angr/angr/blob/master/angr/engines/vex/irop.py). As you can see, there are about ten billion separate ops, so it's not super feasible to implement them all right off the bat, so we do them on an as-needed basis. The Widen ones you posted should be pretty easy for you to do if you can figure out the scheme we're using to genericize the ops, but the floating point ones might be harder.

**Comment by ArtemShypotilov** [comment]
Audrey,

Thanks for the information.
