### ISSUE TITLE
Unable to build libpyvex.so due to missing makefile rule?

### ISSUE THREAD

**Issue by ysf** [angr/pyvex#207]
When checking out the project and trying to build it like the instructions say an error occurs:

```make: *** No rule to make target '/libvex.a?', needed by 'libpyvex.so'.  Stop.```

This breaks angr in the current Archlinux AUR.

**Comment by rhelmot** [comment]
I think we saw this issue once before and it had to do with line ending conversions? The question mark at the end of libvex.a is not supposed to be there, and I think it has to do with line ending conversions.

The way the build process is supposed to work is fairly straightforward as per [setup.py](https://github.com/angr/pyvex/blob/master/setup.py) - if you don't have the libvex sources downloaded, it warns you and then downloads them, otherwise it builds libvex first and then passes the path to the built libvex to the pyvex makefile as an environment variable.

**Comment by ysf** [comment]
It has to do with using the hacky whitespace-in-filenames fix in Makefile.
