### ISSUE TITLE
How hard is it to compile a own version of valgrind vex and integrate it into pyvex?

### ISSUE THREAD

**Issue by b4sic4lly** [angr/pyvex#36]
Hello, 

I was wondering how hard it is to use my own version of valgrind vex to use with pyvex? I have seen that you are using the vex version of angr/vex which has a lot of patches. Is it possible even possible to use my own valgrind version? What changes are necessary?

Kind regards
b4sic

**Comment by zardus** [comment]
The important changes are commenting out the JITing code, because that makes a lot of assumptions regarding the host and guest architecture being the same, which pyvex violates. You can see those by searching for `COMMENTED OUT FOR PYVEX` in https://github.com/angr/vex/blob/master/priv/main_main.c.

It's almost certain that some others have piled up as well. We haven't had time to do such maintenance tasks recently due to the CGC, but at some point soon, we're hoping to go through and document our VEX changes better, upstream fixes, and hopefully find (or recruit?) some manpower to get some VEX changes done so that we don't have to maintain a separate fork.

**Comment by zardus** [comment]
Feel free to reopen this if you have more questions!
