### ISSUE TITLE
Pyvex depends on cffi

### ISSUE THREAD

**Issue by crowell** [angr/pyvex#45]
the pip package cffi is a dependency for pyvex. It's not installed by default on all Python distributions, so it should be added.

**Comment by rhelmot** [comment]
I'm not sure what you're talking about. This is from setup.py:

```
setup(
    name="pyvex", version='5.6.10.5', description="A Python interface to libVEX and VEX IR.",
    packages=['pyvex'],
    cmdclass=cmdclass,
    install_requires=[ 'pycparser', 'cffi>=1.0.3', 'archinfo' ],
    setup_requires=[ 'pycparser', 'cffi>=1.0.3' ],
    include_package_data=True,
    package_data={
        'pyvex': ['lib/*', 'include/*']
    }
)
```

cffi is very clearly a dependency.

It's possible you're running into a problem because you don't have libffi-dev or your distribution's equivalent installed. We mention that you need this in the [https://docs.angr.io/INSTALL.html](install instructions).

**Comment by crowell** [comment]
Weird, on macos Sierra pip install angr failed until I separately pip
installed cffi
