### ISSUE TITLE
How to install pyvex on arm

### ISSUE THREAD

**Issue by frapik99** [angr/pyvex#50]
Hi,
when I try to install pyvex on an a ARM architecture I have the following error:

```
cc1 error: ..... Bad address
now working compiler found....
```

Do you have an idea on how to fix it?

Thanks

**Comment by rhelmot** [comment]
We have never attempted to install pyvex on a non-Intel platform. It should work, since valgrind works on ARM, but there might be some problems with either the vex multiarch support or any part of the pyvex C code. The error message really doesn't say anything that could indicate what's wrong here. 

Unfortunately, getting pyvex to run on non-intel hosts is not a priority right now and we all are very busy with other work, so no guarantees on when this will be fixed...

**Comment by frapik99** [comment]
@rhelmot Thanks for the clarification, I was able install angr and all its deps on an ARM architecture. I'll let you know if everything works against some simple project.

**Comment by frapik99** [comment]
@rhelmot I managed to have angr working on ARM but PyVEX does not properly work:

```
VEX: ARM architecture level is not supported
     Found: ARMv0
Traceback:
Segmentation fault
```

Do you have an idea where I can have a look an how to fix it please? I cannot understand from where that message comes from.

Thanks

**Comment by rhelmot** [comment]
My guess is that your ARM board does not have the hardware capabilities to
run VEX, at least according to VEX. I don't know if this is true or not.

**Comment by frapik99** [comment]
Is there a way to verify it?

**Comment by rhelmot** [comment]
I will look into this as soon as my classes are over, on Thursday. Can you
send me the model of your arm board?

In the meantime, if you want to sanity-check your situation, you can try to
install and run valgrind. If valgrind runs, angr should definitely be able
to run!

**Comment by frapik99** [comment]
@rhelmot Thanks for that, I have installed angr on my android phone. I used the app GNURoot

**Comment by frapik99** [comment]
Hi @rhelmot, I image you are busy now but I would like to know if you are working on it. No pressure :)

**Comment by rhelmot** [comment]
Hey. This took me a while to test since I don't have an arm device onhand and had to use qemu-system to emulate it, which took nearly forever, but I did isolate the problem and just pushed a fix to pyvex.

Note that in the meantime, we've made some updates to our fork of vex, so you should pull that too.

**Comment by frapik99** [comment]
HI @rhelmot, I'll try it in these days and let you know.

Thanks for your help

**Comment by frapik99** [comment]
@rhelmot I think we are almost there... I have compiled vex but based on the official repository I should install it using ```make install``` after it was compiled but it is not possible because the target ```install``` is not present. Can you tell  mex how to install vex? I would suggest to add it also to the README.md

I have installed a new version of pyvex and I had an error on line 6 I think within the function ```size_bits```. I'm not sure about the name. So I have installed the latest version of simuvex and now i cannot import SimIRSB anymore. What do you suggest? Use another virtual env or reinstall something?

Thanks

**Comment by rhelmot** [comment]
pyvex should know how to compile vex automatically, so you should never have to build/install vex yourself. There are two ways pyvex can do it:

- the way that happens if you use setup.sh is that setup.sh clones our fork of vex into the same folder as pyvex. The pyvex build will search in the directory above itself for this folder, and if so, use it.
- the way that happens if you're installing from pip is that pyvex will fail to find vex in the folder above it, so it'll download the latest copy of our fork of vex into `pyvex/vex-master`, then build that.

Your description of the error is too vague of me to say anything other than you probably are still using a copy of pyvex that was built with an old version of vex.

With regard to z3, z3-solver's automatic build process won't work for you because of the thing with armhf builds of z3 needing the `-fpic` flag added manually. You'll need to install z3 on your own. A correct fix for this would involve a pull request to z3.

**Comment by frapik99** [comment]
@rhelmot I have successfully installed z3 manually as you suggested. A pull request would be really nice.

For one time I was able to create a new angr project on my ARM tablet but when I tried to create the cfg. I received an error about the decl ```2353``` I think. So I tried to reainstall simuvex and pyvex after cloning them from github but now I have an error like ```ARMv0 architecture not supported```. I'll try to fix it on my own but do you have any clue on what am I doing wrong?



Thanks

**Comment by rhelmot** [comment]
The newest pyvex should solve the ARMv0 bug, this is the commit that did it: https://github.com/angr/pyvex/commit/dc0a0802688893a3ab4b79faa57f2613b129c472

Make very sure that the version you have installed is the one you think it is - you can check where the module you're actually is coming from by importing the module and then just printing the module object and looking at the filename.

**Comment by frapik99** [comment]
@rhelmot i have installed the latest commit using ```pip git+git://github.com/angr/pyvex@dc0a080 as you said. I have installed the latest version of claripy and simuvex from github but I have the same error:

```
decl 2353 in the solver.py plugin
```

Any idea?

Thanks again

**Comment by rhelmot** [comment]
Can you post the following things:

- The actual backtrace of the error
- The output of `import claripy; import z3; print z3.z3core.lib()`. Ideally this should be a string ending with `site-packages/z3/lib/libz3.so`

**Comment by frapik99** [comment]
@rhelmot I'm sorry but I don't have the full backtrace. The last line is:

```
File "build/bdist.linux-armv71/egg/claripy/backends/backend_z3.py", line 340, in _abstract_internal
```

As a side note, I'm running python from within the z3-solver directory at the same level of the z3 directory. If I don't do that I have an error importing angr. SimIRSB cannot be imported...

The output of the command is: ```<CDLL '/root/Desktop/envs/angr/lib/libz3.so', handle 3bca00 at b64036f0>```

Thanks

**Comment by rhelmot** [comment]
Please delete `/root/Desktop/envs/angr/lib/libz3.so`. It is a holdover from the old system we had for managing the z3 installation, and is almost certainly an old version of z3. Does that help?

**Comment by frapik99** [comment]
Once I remove it should I reinstall z3-solver?

**Comment by rhelmot** [comment]
No. z3-solver should already have installed its own copy of libz3.so.

One thing you should do is to run `import z3; print z3`. If it ends with `z3.py` instead of `__init__.py`, you are using an old version of the z3 python bindings as well, and you should run `pip uninstall angr-only-z3-custom`.

**Comment by frapik99** [comment]
I tried that command and I have z3/__init__.pyc

**Comment by rhelmot** [comment]
Great, then you should be able to delete the file and things should work.

**Comment by frapik99** [comment]
I'm sorry but I have the same error. As a side note, when I create the project I have a warning: ```Unknown reloc 160 on ARMEL```

**Comment by rhelmot** [comment]
The unknown reloc is usually not a problem. It represents an ELF relocation we haven't implemented in CLE.

I don't know what to tell you with regard to your issue. If I had shell access to your machine I would examine each of the angr projects and ensure it was installed correctly, but I really don't know how to serialize that knowledge for you.

My suggestion at this point is to start with a new virtualenv, since it sounds like your current one is fucked.

- Make a new virtualenv
- install z3-solver with the `-fpic` fix
- Clone angr-dev
- `./setup.sh`

**Comment by frapik99** [comment]
@rhelmot thanks for your suggestion. I'm trying now and let you know.

I assume that even if I don't specify -E to setup.sh it will install everything in the current virtual. I'm also worried that even if I have installed z3-solver manually setup.sh will try anyway to install it and I could face some error.

Thanks again

**Comment by rhelmot** [comment]
Your first assumption is correct.

z3 will not be rebuilt by setup.sh if it is already installed, since it is
referenced only as a dependency of claripy.

**Comment by frapik99** [comment]
I have compiled z3 and while in the virtual env I have done ```make install``` but now I have execute ```setup.sh``` and it is compiling z3.

**Comment by rhelmot** [comment]
Shit. I had not considered that `make install` with z3 does not register the python package, so to dependencies, it will look like z3 is not installed. I am working on a pull request to address this, and then I will write a patch to fix the `-fpic` issue.

You should install claripy from the repo.

I'm really sorry that this is such a trial. Installing these packages is a really complicated affair that I've done my best to smooth over, but when things break they break badly and in non-obvious ways.

**Comment by rhelmot** [comment]
`-fpic` pull request submitted: https://github.com/Z3Prover/z3/pull/854

**Comment by frapik99** [comment]
Hi,
in the end I solved the issue installing everything as you said. As a side note, I had to reinstall capstone manually because i wasn't able to import _capstone from capstone. Once done that all worked.

Thanks

**Comment by frapik99** [comment]
I have reopened it because maybe someone wants to add a comment...

**Comment by rhelmot** [comment]
People can comment on closed issues. :)
