### ISSUE TITLE
mipsel register-temp clash

### ISSUE THREAD

**Issue by nimrodpar** [angr/pyvex#75]
Here's part of some translation:
```
------ IMark(0x4e47e4, 4, 0) ------ ; 0x4e47e4: move    $s0, $v0 (size = 4)
t1 = GET:I32(r2)
PUT(r16) = t1
------ IMark(0x4e47e8, 4, 0) ------ ; 0x4e47e8: lui     $t1, 0x19 (size = 4)
PUT(t1) = 0x00190000
```
The first instruction creates a temporary named `t1` (as the normal convention for pyvex), but things get iffy in the second instruction, where `t1` is actually a mipsel register.

It could be that the code generated is still valid, but i was relying on a separation between VEX temporaries and registers. Moreover, this just makes me feel bad, and i'm guessing you too?

**Comment by zardus** [comment]
They're definitely two different `t1`s (the latter is just a name for pretty-printing). The name collision is unfortunate, though.

**Comment by rhelmot** [comment]
You... really shouldn't be relying on the string representation of registers. This is weird for viewing, but it shouldn't ever be a hindrance to analysis, since on every other level but pretty-printing the registers are just integer offsets.

I think the correct solution is to change the way we do our pretty printing to print regs as `tempX` or something, since t1 is in face the real name of that register.

**Comment by nimrodpar** [comment]
Yeah i started using the offsets instead of actual register names. It would be better to do that `tempX` rename since we (and other i think) did somewhat rely on a consistent naming, but no biggie
