### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by Inferno42** [angr/pyvex#83]
Hello,

I've been pulling my hair out for a while trying to figure out this issue. When I try to install pyvex through pip I end up getting this error:
main_util.c
priv/main_util.c(241): fatal error C1083: Cannot open include file: 'stdarg.h': No such file or directory NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"' : return code '0x2' Stop. error: Unable to build libVEX.

I have Visual Studio 2017 installed and the installation seems to successfully set up several other C files such as main_global.c, ir_inject.c, ir_opt.c and more. I have tried running the installation through both Anaconda 2.7 and Python 2.7. if you happen to know of any way to fix this issue that would be greatly appreciated.

**Comment by rhelmot** [comment]
Your issue seems to be unrelated to vex, but rather to something about your visual studio environment. VEX requires almost nothing in terms of a C environment, but does need stdarg.h in order to compile functions with varargs. I would google your error elsewhere. You might run into issues since most solutions out there will target the Visual Studio IDE, and you'll have to figure out how to reapply them to our nmake/cl-based setup, but they should apply. I would also try to compile some small test programs in the visual studio IDE and make sure those work first.

**Comment by projectbtle** [comment]
Just adding this in case it helps anyone. Hopefully, it doesn't result in reopening the issue.

You need to initialize Visual Studio tooling within the virtual environment first, using `"%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86`  (Visual Studio 2015) or `"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"` (Visual Studio 2017 upwards). 

You may need to change the version and arch (64-bit vs. 32bit), according to your setup.

**Comment by ltfish** [comment]
My usual solution is to manually run the "Visual Studio 20?? native developer command prompts X64," then switch to my virtual environment and start compiling pyvex.
