### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by nevilad** [angr/pyvex#86]
Hi,

I'm trying to install pyvex on windows using pip and it fails with "Unable to build libVEX." error. 
During debugging of the install process I figured out:
1) vcvarsall.bat, which is responsible for setting the Visual Studio build environment, is not called. Thus the setup cannot find nmake. So far I now, there is a lot of python packages which do this and their code can be used as example.
2) I've ran this bat-file by hand and got errors in compiling of vex. Sources of vex have .c extension, thus Visual Studio compiles them with C-compiler. In many places definitions of variables are placed not at the beginning of functions, which leads to error C2143. For example:

   Int     i, j;
   Bool    isPut;
   IRStmt* st;
   UInt    key = 0; /* keep gcc -O happy */

   vassert(pxControl < VexRegUpdAllregsAtEachInsn);

   HashHW* env = newHHW();                  //error C2143

   should be rewritten as

   Int     i, j;
   Bool    isPut;
   IRStmt* st;
   UInt    key = 0; /* keep gcc -O happy*/
   HashHW* env;  //moved this definition to the others, before any code.

   vassert(pxControl < VexRegUpdAllregsAtEachInsn);

   env = newHHW();

    You can use /TP switch in CCFLAGS to force VS to use C++ compiler and then the above errors are not generated, but this leads to a bunch of C2440 errors (no explicit conversion from one pointer type to another). For example:

   e2   = cas->expdHi ? flatten_Expr(bb, cas->expdHi) : NULL;

   should be rewritten as

   e2   = cas->expdHi ? flatten_Expr(bb, cas->expdHi) : (IRExpr*)NULL;

   I was unable to find options to compile the code without errors without modifications and don't know which choice (use C or C++ compiler) is better.
3) object files in common.mk have the extension .o, but Visual Studion generates .obj. Thus the linker cannot find files. Changing the extension solves the problem.

**Comment by rhelmot** [comment]
So this is pretty weird, since I've been using pyvex on windows for the last two months without issue.

For starters, we expect you to already have the dev tools loaded in your environment, e.g. by using the visual studio developer command prompt. Calling vcvarsall directly seems like a huge can of worms, considering that a) multiple versions of it can be installed on a given system, b) makes it a serious struggle to do cross compiling (something that I have to do for distributions), and c) requires a registry lookup and complicated logic to handle registry lookups and versioning (e.g. visual studio 2017 has changed vcvarsall to VsDevEnv) which honestly I don't think belongs in the codebase.

As far as I'm aware, libVEX is a c99 + gnu extensions codebase. We hacked around the gnu part with preprocessor macros, but you do need visual studio 2015/2017 in order to compile it.

Finally, I'm not sure what you're talking about with the .obj issue. If you look at the bottom of [the makefile](https://github.com/angr/vex/blob/master/Makefile-msvc) you'll see that we compile each object individually, setting the output to a .o file.

**Comment by ltfish** [comment]
> Calling vcvarsall directly seems like a huge can of worms, considering that a) multiple versions of it can be installed on a given system

This is my No.1 concern. I'm working on a system with a few different versions of Visual Studio installed. I don't think there is an easy way for us to automatically decide which version to use.

**Comment by nevilad** [comment]
Running vcvarsall.bat manually solves the problem. Parts 2 and 3 were due to usage of an older Visual Studio.
Would be nice when the setup, in case of failure, would print that the user, in case of Visual Studio usage, should call vcvarsall.bat manually and that the minimal supported version is 2015.

**Comment by ltfish** [comment]
> that the minimal supported version is 2015.

I used to make it work on VS 2010. Not sure about nowadays.
